(TeX-add-style-hook
 "cap_estadodelarte"
 (lambda ()
   (LaTeX-add-labels
    "chap:estadodelarte"
    "sec:conceptos"
    "fig:estudioPew"
    "sec:historia"
    "sec:a_favor"
    "fig:web_proxy"
    "fig:proxy_cache"
    "fig:trans_proxy"
    "fig:proxy_chain"
    "fig:dyn_chain"
    "fig:strict_chain"
    "key"
    "fig:IPtypes"
    "fig:tunnelMode"
    "fig:norm_Daugman"
    "fig:I2PTunneling"
    "fig:TorPwd"
    "fig:controller"
    "fig:StemOut"
    "fig:hiddenserviceonline"
    "fig:onionshare"
    "fig:onionsharehiddenservice"
    "sec:identificacion"
    "fig:tortazo"
    "sec:social"))
 :latex)

